# Generated by Django 4.1.2 on 2022-11-06 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_airport', models.CharField(max_length=256)),
                ('to_airport', models.CharField(max_length=256)),
                ('departure_date', models.DateField()),
                ('return_date', models.DateField()),
                ('travel_type', models.CharField(max_length=256)),
                ('adult', models.IntegerField()),
                ('children', models.IntegerField()),
                ('infants', models.IntegerField()),
            ],
        ),
    ]
